/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-qjALldgqjf0Kzq9JXRUrwcMexWXRumF5qbFtqu1ujYZOYuV-oryg8sOQD5ofguZDisJwYHc2MPraSRYVr1JJ76DVQv3pFqqyeofL0wyvLfuftrXhsumy1QWI",
  "tt": "tt-1-Nwj7MV5flKqEV5U8PX4099frxxozXvCcNCnPCZEv8bI=",
  "version": "2020-11-20"
}

export default ebconfig;